name: CD

on:
  push:
    tags: 
      - '*'
      - "!daily-*"

jobs:
  docker-push:
    name: Push to container registry
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build relic
      run: make crypto_setup_gopath
    - name: Docker build
      run: |
        make docker-build-flow
        make docker-build-flow-without-netgo
